README.org ---  description



Copyright (C) 2009 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>

  

  This file is part of geda_library.
  
  geda_library is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  geda_library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with geda_library.  If not, see <http://www.gnu.org/licenses/>.
  
  
  
* Keywords:
  
  

* Description:
  
  
  
* Usage:
  
  read with emacs (3__3) org mode
  
  
  
  
* History:
  
  initial project version began about 2009.10(Oct).20.
  
* Dependences:
* Code  


  > create a hierarchy?  

(1) Create each page as a separate .sch file.

(2) Use the autonumbering dialog to number your parts, with refdes starting 
from 100 on the first page, 200 on the second page, 300 on the third page, 
etc.

refdes_renum --force --pgskip 100 1.sch
refdes_renum --force --pgskip 200 2.sch

(3) Put *all* the .sch files as arguments to the gnetlist (or gsch2pcb) 
invocation.

  
  
имена должны быть в таком виде (не нужно использовать "-")


r_aeou5
|||   |
|||   |
|||   L цифирка
|||
||L слово или буква
||
|L подчёркивание
|
L буква или слово

gsch2pcb --help  говорит что стандартные пути для footprint:
/usr/local/share/pcb/newlib, /usr/share/pcb/newlib, (old pcb) /usr/local/lib/pcb_lib, /usr/lib/pcb_lib, (old pcb) /usr/local/pcb_lib

найти все ошибки:
gnetlist -g drc2 Seven-segment_display.sch -o drc_output.txt

построить netlist (наверное это лишнее):
gnetlist -g spice-sdb -o z.net Seven-segment_display.sch


gsch2pcb -d ../footprints Seven-segment_display.sch







Next steps:
1.  Run pcb on your file Seven-segment_display.pcb.
2.  From within PCB, select "File -> Load layout data to paste buffer"
    and select Seven-segment_display.new.pcb to load the new footprints into your existing layout.
3.  From within PCB, select "File -> Load netlist file" and select 
    Seven-segment_display.net to load the updated netlist.

4.  From within PCB, enter

           :ExecuteFile(/home/chujoii/rel/Seven-segment_display/Seven-segment_display.cmd)

	   (":" не нужно если через меню)

    to update the pin names of all footprints.



psselect 3 Seven-segment_display.ps z.ps

--------------------------------------------------------------------------------
новая версия

для SOT23 (Small Outline Transistor) транзистора нужно указать базу коллектор эмиттер (сток исток затвор)


http://www.geda.seul.org/wiki/geda:transistor_guide
Surface Mount Transistors: The SOT (Small Outline Transistor) packages are much more standard than the TO packages and the pins are consistently numbered counterclockwise from the top left as are IC packages. But for a transistor that has a TO and a SOT version, you can't simply change the footprint attribute on the schematic because the package pin numbers don't map the same to the emitter, base, and collector. You need a separate gschem symbol for them. For example: 2N3904.sym for the TO and MMBT3904.sym for the SOT.


http://www.geda.seul.org/mailinglist/geda-user60/msg00042.html
http://www.geda.seul.org/wiki/
http://www.geda.seul.org/mailinglist/geda-user60/msg00060.html
https://bugs.launchpad.net/geda/+bug/698821

less /usr/share/gEDA/sym/analog/nmos-3.sym


гребёнка или колодка штырьков
PBS-10 однорядный,10 контактов
PBD-40 двухрядный, 2 ряда по 20 контактов

Если в конце R то угловой.
Ответная часть по томуже принципу маркируется только PLS/PLD 



* xgsch2pcb
  
  после создания файла *.gsch2pcb
  добавить в него пути к footprint:
  -------- -------- 8< -------- --------
  ...
  elements-dir /home/chujoii/project/geda/footprints-geda
  elements-dir /home/chujoii/project/geda/footprints-my
  ...
  -------- -------- >8 -------- --------

  
  файл ~/.gafrc должен выглядеть примерно так:
  -------- -------- 8< -------- --------
  ...
  (component-library "/home/chujoii/project/geda/symbols-my")
  (component-library "/home/chujoii/project/geda/symbols-geda")
  
  или так
  (source-library "…")
  (component-library "${HOME}/geda/symbols/analog")
  (component-library
  "/envy/dj/geda/gedasymbols/www/user/dj_delorie/symbols/misc"
  "gedasymbols/dj/misc") ; Any character is valid in this argument.
  ...
  -------- -------- >8 -------- --------


  Don't use diode-1.sym when using PCB
  diode-3 is OK.

* sym
 

на ножке "ee" вызывает редактирование
 

| pintype | description               |
|---------+---------------------------|
| in      | Input                     |
| out     | Output                    |
| io      | Input/Output              |
| oc      | Open collector            |
| oe      | Open emitter              |
| pas     | Passive                   |
| tp      | Totem pole                |
| tri     | Tristate (high impedance) |
| clk     | Clock                     |
| pwr     | Power/Ground              |
|         |                           |

